### ISSUE TITLE
segfault when correcting gopro lens

### ISSUE THREAD

**Issue by ksamak** [seebk/GIMP-Lensfun#11]
Problem with Gopro© lens correction: 
No problem building, or copying to right gimp folder.
but when i open the window, and choose the gopro maker, there's no camera, or lens.
But there's a focal length and aperture, so i click OK. then i can see on the command line that gimp-lensfun has segfaulted.

i'm on debian wheezy, gnome3. all versions standard wheezy versions.
i'll try and start gdb to explore a little.

at commit a898ecd5492a8b6294fcfda684548345ffb0b0df:
make:
g++ -DDEBUG=0 -O3 -Wall -fopenmp -pthread -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/gimp-2.0   -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/   -c -o src/gimplensfun.o src/gimplensfun.cpp
src/gimplensfun.cpp: In function ‘void query()’:
src/gimplensfun.cpp:205:5: warning: deprecated conversion from string constant to ‘gchar* {aka char*}’ [-Wwrite-strings]
src/gimplensfun.cpp:205:5: warning: deprecated conversion from string constant to ‘gchar* {aka char*}’ [-Wwrite-strings]
src/gimplensfun.cpp:205:5: warning: deprecated conversion from string constant to ‘gchar* {aka char*}’ [-Wwrite-strings]
src/gimplensfun.cpp:205:5: warning: deprecated conversion from string constant to ‘gchar* {aka char*}’ [-Wwrite-strings]
src/gimplensfun.cpp:205:5: warning: deprecated conversion from string constant to ‘gchar* {aka char*}’ [-Wwrite-strings]
src/gimplensfun.cpp:205:5: warning: deprecated conversion from string constant to ‘gchar* {aka char*}’ [-Wwrite-strings]
g++ -o gimp-lensfun src/gimplensfun.o -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lglib-2.0   -L/usr/lib/ -llensfun -lglib-2.0 -lexiv2   -lstdc++ -fopenmp

**Comment by seebk** [comment]
This should now be fixed in the current release.
