### ISSUE TITLE
gimplensfun.cpp:757: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [seebk/GIMP-Lensfun#12]
[src/gimplensfun.cpp:757]: (warning) Logical conjunction always evaluates to false: x >= 2 && x <= -2.

  if ( (x >= cLanczosWidth) && (x <= (-1)*cLanczosWidth) )

Maybe

  if ( (x >= cLanczosWidth) || (x <= (-1)*cLanczosWidth) )

**Comment by seebk** [comment]
You are right, that was wrong. It is fixed now.
