### ISSUE TITLE
used installer now gimp gives me error code on opening

### ISSUE THREAD

**Issue by jadelyf** [seebk/GIMP-Lensfun#13]
gimp says "unable to open application blah blah error code blah blah" Please advise... I can't even find the program files to delete them
![blahblahblahfuckyou](https://cloud.githubusercontent.com/assets/15273656/10711599/da403834-7a35-11e5-8f02-dd890636bf47.png)

**Comment by jadelyf** [comment]
found the file and deleted it, but the installer put it in the wrong folder and the plug in doesn't work

**Comment by seebk** [comment]
Sorry, as stated on the website the windows installer is experimental and we cannot give support for it as we do not have a regular windows maintainer and expert.
