### ISSUE TITLE
0.24 compilation failure - lfDatabase() is protected

### ISSUE THREAD

**Issue by Beep6581** [seebk/GIMP-Lensfun#14]
Hello

Compilation of 0.24 fails with:
```In file included from src/gimplensfun.cpp:30:0:
/usr/include/lensfun/lensfun.h:1603:5: error: ‘lfDatabase::lfDatabase()’ is protected```

Full log here:
https://dpaste.de/RpJ6

GCC-4.9.3, GIMP-master.

**Comment by seebk** [comment]
Sorry, I should have mentioned in the release log that the most recent Lensfun version 0.3.2 is required for building. If you want to build against an older version please simply revert commit 1ba1aa.

(Maybe I should have kept using the old API in GimpLensfun until version 0.3.2 has spread.... :/ )

**Comment by Beep6581** [comment]
I opened requests for an addition of both media-libs/lensfun-0.3.2 and media-plugins/gimp-lensfun-0.2.4 to Gentoo. I think we can close this.
