### ISSUE TITLE
Wrong lens detected for Fujifilm X-E2

### ISSUE THREAD

**Issue by horsteff** [seebk/GIMP-Lensfun#18]
For a picture shot with a Fujifilm X-E2 the GIMP-Lensfun dialog shows the wrong lens. Especially instead of the XF 18-55mm f/2.8-4 R LM OIS the XC 16-50mm f/3.5-5.6 OIS is shown.

It seems that the code doesn't read the lens model from Exif data for Fujifilm cameras (and others without special maker handling) and selects the first lens it finds instead.

As the X-E2 stores lens model in "Exif.Photo.LensModel" and this is a Exif 2.3 standard tag for the lens model, I created a patch to use this tag for all makers without a special handling. The attached [default_lens_patch.zip](https://github.com/seebk/GIMP-Lensfun/files/681156/default_lens_patch.zip) contains the patch and a little image file with necessary Exif data to test the patch for Fujifilm X-E2 and XF 18-55mm f/2.8-4 R LM OIS.

**Comment by seebk** [comment]
Thanks for your patch and sorry for the late reply. It is now in master.
