### ISSUE TITLE
Lensfun won't install properly on Gimp 2.8 with Windows 10

### ISSUE THREAD

**Issue by Anoneemouse** [seebk/GIMP-Lensfun#19]
I'm using Gimp 2.8 with Windows 10.  I could REALLY use lensfun, but it doesn't install properly.  Every time I open Gimp I get a popup dialogue box saying that it couldn't load, and I have to click ok for Gimp to finish opening.  Then it's not available in any of the menu selections.  I've copied the error message below.  I very much hope someone can fix this - or at least tell me what files lensfun loads and where each ought to be on my computer so I can check each and move them where they belong so lensfun will work.  

![gimp lensfun fail](https://cloud.githubusercontent.com/assets/16356703/26023551/2be4b9e8-3773-11e7-8384-425a88449843.jpg)

**Comment by seebk** [comment]
See #20
