### ISSUE TITLE
Lensfun not installing - windows 7 Gimp 2.8

### ISSUE THREAD

**Issue by JulieMay** [seebk/GIMP-Lensfun#20]
I know that lensfun isn't supporting Windows. I just want the issue documented.

When I tried to install with the various installers (I tried the newest first) none of them would work. 
The newest installer caused the error and none of the others seemed to install something that helped to fix it. So, the error is from the newest installer. 

When Gimp Startup opens an error comes up
  gimp-lensfun.exe - Application Error. The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by seebk** [comment]
The GIMP Lensfun windows package is experimental and there is no one who is able to maintain it on a regular basis. Hence, there won't be a fix soon. Sorry... 
#19
